### PR TITLE
Yosys odin mult

### PR DESCRIPTION
**Pull request by HMoein87**
Provide the model that is required for the partial mapping of multiplication in blif elaborate file

#### Description

The condition of supporting for multiplication sub circuit is added.
The model required for partial mapping of multiplication is added in blif elaborate file

#### Motivation and Context

This work is a continuation of performing partial mapping for output files come from Yosys.
 
#### Types of changes

- [ ] Bug fix (change which fixes an issue)
- [*] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:

- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by sdamghan** [comment]
@HMoein87 Are you sure you compiled the code? When I run the code it shows a segmentation fault! the solution is not complete yet, it needs much more adjustments in the codebase!

**Review by HMoein87 — COMMENTED** [review]
repository updated and issues resolved.

**Comment by sdamghan** [comment]
@HMoein87 it still shows errors! Would you please have deep look at the code?

**Comment by sdamghan** [comment]
I will add a complete CI test for generated blif files, it should be good to use the verify_odin script to check the Odin's functionality on those

**Pull request closed without merging**
